[build]
    base    = "cmd/hugothemesitebuilder/build/site"
    publish = "public"
    command = "./build.sh"
    ignore  = "/bin/false"

[context.production.environment]
    HUGO_VERSION = "0.102.3"

[context.deploy-preview.environment]
    HUGO_VERSION = "0.102.3"

[context.branch-deploy.environment]
    HUGO_VERSION = "0.102.3"
